travis:
  secure:
    BINSTAR_TOKEN: OP6uWWVTInhcM3NaFu/HIawcq7nKbxCVlGhwc2PL5Di3XEfj0TGawAUjm/zns+x8D2K4CAge8NhMqpnfEq0Ig0M2/xf31Il7jwB/6eK/VdjbG5C3Aqi07t63ejtkf5rK6AjwijIL1zid9agmFAOs1rH8JGqy1hwO9TrBOOOW/DqT4j6Z71B8VjYQJ5pqC7CYparqh0h+p//F+/joJxlM9W1POEan09+pYhAqFBBDGOK/k3RMzwhKR9suA/0n71U1Q3ysI2nfN9+bbBc+bb+YPBPJg/Rz0NA57r4w8hPhPXyBfu8uER4spTzh7qLLAJPxB6OBTndG7bivhvkzfWmnuBnVWyLZewt6xG+dEBmTCBFKiG4+nMsa6GsOLRtOUpXIX3MOoPKrVj0IYSQw+fs0OHX9wfufpt/Rth17/e3b94yfmO0PU0vkqvpIqnyvNtfU/L3Wf6fJbxXseo1qJwdX/F7bT/20Ff9eE6ERBPUy/Gn+cxbXOV/5t1iwgf2gAx4NsdEQJboI0oK166nV/Gmqt6Z+3eqE+O2+TiC9tLEwYBozLIOndyWubujgtggEi7B9CbbVfXdOwERfM7sX7h7W9LpPJEcoarO3cp2HGL/DqlFAG6BLoE5fusmaEXY2u4olyylZ2Z/kPKNvjRZzsZur6wrUOfSTdWTpusfmu83VHHY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
